
---
title: "Chapter 1"
author: "Kisun Pokharel"
output: html_document
---
# Tools and Methods for open and reproducible research

The first week of the course covered basic tools and requirements for the rest of the weeks. I practiced basics of R by completing a [Data Camp](datacamp.com) exercise called ["R Short and Sweet"](https://www.datacamp.com/courses/r-short-and-sweet). In addition I brushed up git and rmarkdown by going through the first workshop as detailed below.

## Rstudio Exercise 1

1. I already had a github account and I just forked "IODS-project" from Tuomo Nieminen's github. 
2. I modified chapter1.Rmd file under IODS-project in Rstudio. Link to my IODS-project repository is [here](https://github.com/kisun/IODS-project).
3. I opened the index.Rmd file and added my name. I commited the change and pushed to my github. 
4. I created a new Rmarkdown file with Rstudio. I wrote few sentences about the course and saved it as README.Rmd under IODS-project. The link to my course diary is [here](https://kisun.github.io/IODS-project/)
5. I replaced the default theme of my course diary web page with **Time Machine** theme.
6. I uploaded all the changes to GitHub.
7. I made sure that all changes could be seen.

Note1: Something that was not mentioned in the course that could be useful or could be included in future. Rstudio works hand-in-hand with github so R scripts or Rmd documents can be directly linked to github. The parent directory of the course (locally downloaded to the PC) can be imported as a github project that can be authorized by one's username and password.

keywords: github, linux, rstudio, rmarkdown 

